name = "SimSpread"
uuid = "afa5cc60-bf5a-45b9-aa6c-27158a106b2a"
authors = ["Carlos Vigil Vásquez <carlos.vigil.v@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
